# -*- coding: utf-8 -*-
"""🔎 PHASE A — HISTORICAL EVIDENCE RECOVERY & CORPUS RECONCILIATION (FAISAL MASTER FORENSIC RECOVERY · A1-A14).

Read-only. Builds the Phase A artifacts from (1) the repository working tree and (2) measurements that cannot be
recomputed in CI, recorded once in `data/phase_a_inputs.json` (session transcript images, session uploads, scratch
images, GitHub listings, git history, Actions logs) and `data/artifact_probe_result.json` (runner-side probe of every
live Actions artifact — `artifact_probe.py`).

    python3 faisal_recovery/phase_a.py build     # writes records, manifests, the six A13 artifacts, A10 table and the A14 seal
    python3 faisal_recovery/phase_a.py --check   # re-renders every artifact from the frozen data and compares byte-for-byte,
                                                 # verifies the seal hashes and that every sealed historical image is unchanged

🔒 V4 is frozen (7c8826c) and is not imported or modified. No Telegram, no network, no production state.
Classification rules (one class per record — A5):
  bytes opened in this mission     → SHA equal to the corpus / another record ⇒ EXACT_DUPLICATE · tool-side downscale of the same
                                     corpus file (same path, pHash distance 0) ⇒ EXACT_DUPLICATE · generated by a tool/assistant
                                     (provenance by code or by the generating command) ⇒ NON_FAISAL · otherwise NEW_TO_CORPUS /
                                     INFORMATIVE_DERIVATIVE (visual check) / UNKNOWN
  bytes not openable now           → identity machine-verified by SHA while accessible (recorded measurement) ⇒ EXACT_DUPLICATE ·
                                     existence measured in a now-lost byte source ⇒ INACCESSIBLE_IMAGE · only a textual ID with no
                                     byte-level record anywhere accessible ⇒ IMAGE_REFERENCE_ONLY · a message claiming an attachment
                                     with no bytes ever ⇒ MISSING_ATTACHMENT
"""
import argparse
import collections
import csv
import datetime as dt
import hashlib
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(HERE, "data")
V4_COMMIT = "7c8826c25e745668d33facabb2efbc488e997fb7"
CORPUS_BEFORE = 769                      # authoritative baseline (768 files + 1 attachment) — reconciled, never overwritten

CLASSES = ("NEW_TO_CORPUS", "EXACT_DUPLICATE", "INFORMATIVE_DERIVATIVE", "IMAGE_REFERENCE_ONLY", "INACCESSIBLE_IMAGE",
           "MISSING_ATTACHMENT", "NON_FAISAL", "UNKNOWN")
ACCESS = ("FULLY_ACCESSIBLE", "PARTIALLY_ACCESSIBLE", "TEXT_ONLY", "METADATA_ONLY", "INACCESSIBLE")
A4_FIELDS = ("IMAGE_ID", "SOURCE_ID", "CONVERSATION_ID", "MESSAGE_ID", "TIMESTAMP", "PATH_REFERENCE", "SHA256",
             "PERCEPTUAL_HASH", "WIDTH", "HEIGHT", "TICKER", "TIMEFRAME", "VISIBLE_DATE", "AUTHOR", "CHANNEL", "VISIBLE_TEXT",
             "PATTERN", "STRUCTURE", "INDICATORS", "ANNOTATIONS", "ENTRY", "STOP", "TARGET", "SUPPORT", "RESISTANCE",
             "FAISAL_DECISION", "PROVENANCE", "CORPUS_CLASSIFICATION")
EXTRA_FIELDS = ("DUPLICATE_OF", "DUPLICATE_OF_CLASS", "CLASS_BASIS", "PRIOR_CLASSIFICATION", "BYTES_OPENED_THIS_MISSION")
CSV_FIELDS = A4_FIELDS + EXTRA_FIELDS

OUT = {
    "sources": "HISTORICAL_SOURCE_ACCESS.md",
    "recovery": "HISTORICAL_IMAGE_RECOVERY.md",
    "inventory": "HISTORICAL_IMAGE_INVENTORY.csv",
    "reconciliation": "HISTORICAL_CORPUS_RECONCILIATION.md",
    "v5": "HISTORICAL_V5_CANDIDATES.md",
    "report": "HISTORICAL_PHASE_A_REPORT.md",
    "decisions": "HISTORICAL_DECISION_FORENSICS.csv",
    "seal": "HISTORICAL_PHASE_A_SEAL.json",
}
FROZEN = {"manifest": "data/historical_manifest.json", "sources": "data/phase_a_sources.json",
          "docrefs": "data/doc_references.json"}
IMG_EXT = (".jpg", ".jpeg", ".png", ".webp", ".gif", ".bmp", ".heic", ".tif", ".tiff")
MAGIC = ((b"\xff\xd8\xff", "jpeg"), (b"\x89PNG\r\n\x1a\n", "png"), (b"GIF87a", "gif"), (b"GIF89a", "gif"), (b"BM", "bmp"))


# ── helpers ──────────────────────────────────────────────────────────────────────────────────────────────────────────
def _p(*a):
    return os.path.join(ROOT, *a)


def _j(rel):
    with open(_p(rel), encoding="utf-8") as f:
        return json.load(f)


def _sha_bytes(b):
    return hashlib.sha256(b).hexdigest()


def _sha_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def canon(obj):
    """Canonical JSON (sorted keys, no whitespace variance) — every hash in the seal is over this form. Pure."""
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def canon_hash(obj):
    return hashlib.sha256(canon(obj).encode("utf-8")).hexdigest()


def sniff(head):
    for sig, kind in MAGIC:
        if head.startswith(sig):
            return kind
    if head[:4] == b"RIFF" and head[8:12] == b"WEBP":
        return "webp"
    return None


def classify_count(records):
    c = collections.Counter(r["CORPUS_CLASSIFICATION"] for r in records)
    return {k: c.get(k, 0) for k in CLASSES}


def rec(**kw):
    """One inventory record with every A4 field present (empty string when not applicable). Pure."""
    r = {k: "" for k in CSV_FIELDS}
    for k, v in kw.items():
        if k not in r:
            raise KeyError(k)
        r[k] = " · ".join(str(x) for x in v) if isinstance(v, (list, tuple)) else ("" if v is None else str(v))
    if r["CORPUS_CLASSIFICATION"] not in CLASSES:
        raise ValueError(f"bad class {r['CORPUS_CLASSIFICATION']!r} for {r['IMAGE_ID']}")
    return r


def pfmt(d256, p64):
    return f"d256:{d256}|p64:{p64}" if d256 or p64 else ""


# ── corpus baseline ──────────────────────────────────────────────────────────────────────────────────────────────────
def corpus_manifest(inputs):
    """The sealed historical corpus: every file in faisal_images/ (SHA256 recomputed now; perceptual hashes from the
    frozen corpus inventory) + the session attachment (from the recorded measurement). Fails loudly on any mismatch
    between the file on disk and the inventory hash."""
    inv = {r["IMAGE_ID"]: r for r in _j("faisal_method_v41/corpus_audit/MASTER_CORPUS_INVENTORY.json")["rows"]}
    rows = []
    folder = _p("faisal_images")
    for f in sorted(os.listdir(folder)):
        if not f.lower().endswith(IMG_EXT):
            continue
        stem = os.path.splitext(f)[0]
        sha = _sha_file(os.path.join(folder, f))
        r = inv.get(stem)
        if r is None:
            raise SystemExit(f"⛔ corpus file without an inventory row: {f}")
        if r["HASH"] != sha:
            raise SystemExit(f"⛔ corpus file changed since the corpus audit: {f}")
        ph = r.get("PERCEPTUAL_HASH") or {}
        rows.append({"id": stem, "path": f"faisal_images/{f}", "sha256": sha, "dhash256": ph.get("dhash256"),
                     "phash64": ph.get("phash64"), "kind": "file"})
    up = inputs["uploads_current"][0]
    rows.append({"id": "ATTACHMENT_" + up["name"].split("-")[0], "path": "session-attachment:" + up["name"],
                 "sha256": up["sha256"], "dhash256": up["dhash256"], "phash64": up["phash64"], "kind": "attachment"})
    return rows


# ── sources (A1) ─────────────────────────────────────────────────────────────────────────────────────────────────────
def sources(inputs, probe, collector, docrefs):
    g, gh, tr = inputs["git"], inputs["github_text"], inputs["transcript_current"]
    pre = _j("faisal_method_v3/v31/reconcile_v31.json")["transcript"]
    sa = {s["id"]: s for s in _j("faisal_method_v3/source_access.json")["sources"]}
    up_prior = sa["SRC-SESSION-UPLOADS"]
    t = probe["totals"]
    S = [
        ("S01", "REPOSITORY_CORPUS", "faisal_images/ at HEAD (the baseline corpus files)", "FULLY_ACCESSIBLE", "FULL", "FULL",
         "2026-06-21 → seal", 768, "Baseline (CORPUS_BEFORE); not candidates — every file re-hashed against the corpus inventory"),
        ("S02", "SESSION_ATTACHMENT_CURRENT", "uploads directory of the current container", "FULLY_ACCESSIBLE", "FULL", "n/a",
         "2026-10-07", 1, "Baseline attachment #769 (owner's blind-test chart · NON_EVIDENCE in the corpus audit) — never pushed"),
        ("S03", "REPOSITORY_OTHER_IMAGES", "tracked images outside faisal_images/ (renders · owner instruction image)", "FULLY_ACCESSIBLE",
         "FULL", "FULL", "2026-08-08 → 2026-10-06", len(inputs["repo_other_images"]), "Generated renders and the owner's operating-standard image"),
        ("S04", "GIT_HISTORY", f"full mirror of every ref: {g['branches']} branches + {g['pull_heads']} pull-request heads "
         f"(+{g['pull_merge_refs']} merge ref) · {g['objects_total']:,} objects ({g['commits']:,} commits · {g['trees']:,} trees · "
         f"{g['blobs']:,} blobs = {g['blob_mb']:,} MB)", "PARTIALLY_ACCESSIBLE", "FULL (reachable)", "FULL",
         "2026-06-21 → seal", g["image_blobs_ever"],
         f"every blob opened: {g['image_blobs_ever']} images by magic bytes = {g['image_blobs_by_path']} by path · all present at HEAD "
         f"({g['history_only_image_blobs']} history-only) · other binary formats {sum(g['magic_other'].values())} · blobs with an "
         f"embedded base64 image {g['embedded_base64_image_blobs']} · {len(g['old_paths'])} historical paths renamed/removed · "
         "objects unreachable from any ref (force-push/GC) are not served"),
        ("S05", "GIT_TAGS", "tags", "FULLY_ACCESSIBLE", "FULL", "FULL", "—", 0, f"{g['tags']} tags"),
        ("S06", "GITHUB_PR_ISSUE_RELEASE_TEXT", f"{gh['pulls']} PR bodies · {gh['pure_issues']} issues · {gh['issue_comments']} issue "
         f"comments · {gh['pull_review_comments']} review comments · {gh['releases']} releases", "FULLY_ACCESSIBLE", "FULL (none present)",
         "FULL", "2026-06 → seal", gh["image_attachments_found"],
         f"{gh['image_attachments_found']} image attachments (patterns: " + ", ".join(gh["patterns_searched"]) + ")"),
        ("S07", "ACTIONS_ARTIFACTS_LIVE", f"{probe['artifacts_listed']} live artifacts listed at {probe['listed_at_utc']} = the evidence "
         f"cutoff (oldest {probe['oldest_created'][:10]})",
         "FULLY_ACCESSIBLE", "FULL (runner-side probe)", "n/a", f"{probe['oldest_created'][:10]} → {probe['newest_created'][:10]}",
         t["image_entries"], f"downloaded {probe['downloaded']}/{probe['artifacts_listed']} on a runner (session proxy blocks blob storage) · "
         f"{t['in_repo']} image entries SHA-identical to repository files · {t['not_in_repo_entries']} entries ({t['not_in_repo_unique_sha']} unique) "
         "are tool renders"),
        ("S08", "ACTIONS_ARTIFACTS_EXPIRED", "artifacts past retention (incl. the 7-day faisal-images safety copies 07-27…09-30)",
         "INACCESSIBLE", "NONE", "NONE", "→ " + probe["oldest_created"][:10], "UNKNOWN",
         f"collector safety copies only: {collector['runs_total']}/{collector['runs_total']} collector runs succeeded (each commits what it "
         "saved before success) ⇒ no image can exist only in an expired copy (strong inference, not a byte check)"),
        ("S09", "ACTIONS_JOB_LOGS", "collector job logs (90-day retention)", "TEXT_ONLY", "NONE", "FULL (read where needed)",
         "2026-07-27 → seal", 0, "Used to classify every Telegram message that was received but not saved (counts · matched pairs · failures)"),
        ("S10", "TELEGRAM_COLLECTOR_RECORDS", "telegram_collect_state.json · telegram_collect_meta.jsonl · report history in git",
         "TEXT_ONLY", "via S01 (saved files)", "FULL", "2026-07-27 → seal", collector["image_messages_total"],
         f"{collector['saved_tg_files']} saved as TG_<msg> files · {collector['accounted_not_saved']} accounted but not saved · "
         f"{collector['dup_numbers_lost']} duplicates whose message numbers were never recorded (07-28) · perm-failed 0"),
        ("S11", "TELEGRAM_BOT_PENDING_UPDATES", "bot getUpdates queue (runner-side, ≤24 h retention)", "FULLY_ACCESSIBLE",
         "FULL (via collector)", "FULL", "rolling 24 h", collector["pending_at_last_run"],
         f"pre-seal drain = collector run {collector['last_run_id']} ({collector['last_run_utc']}): saved 0 · pending 0 · bot offset "
         f"{collector['pre_seal_drain']['offset']} unchanged since {collector['pre_seal_drain']['offset_since']} · verification run "
         f"{collector['cutoff_verification']['run']} ({collector['cutoff_verification']['get_updates_utc']}, after the cutoff): "
         f"{collector['cutoff_verification']['updates_of_any_kind']} updates of any kind ⇒ the queue held nothing at the cutoff"),
        ("S12", "TELEGRAM_CHANNEL_HISTORY", "Faisal's Telegram channel/group history", "INACCESSIBLE", "NONE", "NONE", "—", "UNKNOWN",
         "The bot sees only messages sent to it; channel identity is not recorded in the repository (privacy rule)"),
        ("S13", "X_ACCOUNT", "x.com/kisar_ (posts and images)", "INACCESSIBLE", "NONE", "NONE", "—", "UNKNOWN",
         "Egress blocked (CONNECT 403 for x.com · api.x.com · syndication.twitter.com); no API key; automation is against its terms"),
        ("S14", "SESSION_TRANSCRIPT_CURRENT", "this session's local transcript after the 2026-10-02T21:44Z compaction", "FULLY_ACCESSIBLE",
         "FULL", "FULL", f"{tr['first_ts'][:16]} → {tr['recheck']['cutoff_utc'][:16]} (cutoff)", tr["image_blocks"],
         f"{tr['image_blocks']} image blocks ({tr['unique_images']} unique) · {tr['human_messages']} human messages, "
         f"{tr['human_messages_with_image_blocks']} with an image · re-extracted at seal time: "
         f"{tr['recheck']['first_pass_blocks_identical']}/{tr['recheck']['first_pass_blocks']} first-pass blocks byte-identical in place "
         f"(a second context compaction left the local file intact) + {tr['recheck']['blocks_added_since']} added since"),
        ("S15", "SESSION_TRANSCRIPT_PRE_COMPACTION", "this session before 2026-10-02T21:44Z", "METADATA_ONLY", "NONE (dropped)",
         "summary only", "2026-09-06 → 2026-10-02", pre["owner_sent_blocks"] + pre["tool_result_blocks"],
         f"Dropped at compaction ({inputs['transcript_current']['compaction_dropped_tokens']:,} tokens) · V3.1 measured it while accessible: "
         f"{pre['owner_sent_blocks']} owner blocks ({pre['owner_sent_unique']} unique) + {pre['tool_result_blocks']} tool views "
         f"({pre['tool_result_unique']} unique) · owner images sent between that measurement (2026-10-02 ≤17:34Z) and 21:44Z: UNKNOWN"),
        ("S16", "SESSION_UPLOADS_PRIOR_CONTAINER", "uploads directory of the previous container", "METADATA_ONLY", "NONE (container reset)",
         "NONE", "2026-09 → 2026-10-02", up_prior["count_files"],
         f"V3 measured {up_prior['count_files']} image files ({up_prior['unique_by_sha']} unique) + 2 PDF + 1 audio + 1 text; "
         "only the classification survives (faisal_method_v3/source_access.json)"),
        ("S17", "PDF_FAISAL_GUIDE", "«دليل طريقة فيصل» (94 pages, 78 embedded images)", "TEXT_ONLY", "NONE", "repository extracts",
         "—", 78, "Not in this container and never pushed (public repository rule); cited pages PDF_B_p25/26/27/52/76 survive as text"),
        ("S18", "PDF_ELLIOTT_GUIDE", "Elliott-wave guide (57 pages, 48 images)", "TEXT_ONLY", "NONE", "FAISAL_ELLIOTT_NOTES.md", "—", 48,
         "Not in this container and never pushed; V3 found 0 corpus matches (generic educational images)"),
        ("S19", "AUDIO_RECORDING", "voice recording + machine transcript", "INACCESSIBLE", "n/a (audio)", "NONE", "—", 0,
         "No images; not in this container; never pushed"),
        ("S20", "REPOSITORY_TEXT_REFERENCES", "image IDs named in repository text with no file", "TEXT_ONLY", "NONE", "FULL",
         "2026-06 → seal", docrefs["counts"]["reference_only"],
         f"{docrefs['counts']['files_scanned']} text files scanned with rules R1-R6 · {docrefs['counts']['reference_only']} IDs without bytes · "
         f"{docrefs['counts']['resolved_by_name']} abbreviations resolved to corpus files · {docrefs['counts']['excluded']} non-references excluded"),
        ("S21", "CHART_CARDS", "chart_cards/ number cards of owner images", "TEXT_ONLY", "NONE", "FULL", "2026-09-24 → 2026-10-07", 5,
         "Cards describe 4 prior-container uploads (S16) and the current attachment (S02) — mapped, not counted twice"),
        ("S22", "OTHER_CLAUDE_SESSIONS", f"{inputs['sessions']['project_related']} project-related + {inputs['sessions']['other']} "
         "other Claude sessions on the account", "METADATA_ONLY", "NONE", "titles/status only", "2026-06-21 → 2026-10-08", "UNKNOWN",
         "No tool in this session reads another session's transcript or attachments"),
        ("S23", "OTHER_REPOSITORIES", "Super_StocksX · Split_Hunter_Kronos · Superx1 (all refs)", "FULLY_ACCESSIBLE", "FULL", "FULL",
         "2026-06 → 2026-10", 0, "0 image blobs in any reachable object"),
        ("S24", "OTHER_REPOSITORY_SUPER_STOCK2", "super_stock2 (June session repository)", "INACCESSIBLE", "NONE", "NONE", "2026-06",
         "UNKNOWN", "Not attachable to this session"),
        ("S25", "CLAUDE_AI_ARTIFACTS", "8 artifacts listed on the account + 1 linked from a session", "PARTIALLY_ACCESSIBLE",
         "1 project artifact read (0 images)", "titles", "2026-07 → 2026-09", 0,
         "7 artifacts are non-project by title · «exploder-analysis» (2026-07-12) could not be read: «artifact not found»"),
        ("S26", "CONNECTORS", "Gmail · Google Drive · Calendar", "INACCESSIBLE", "NONE", "NONE", "—", "UNKNOWN", "Not connected"),
        ("S27", "SCRATCHPAD", "assistant-generated images in this session's scratchpad (recovery/ excluded: this mission's own "
         "byte copies of S07/S14 and the git mirror)", "FULLY_ACCESSIBLE", "FULL", "n/a",
         "2026-10-07", len(inputs["scratch"]), "Crops/composites generated from corpus files or the attachment (generator command on record)"),
        ("S28", "LOCAL_TOOL_LOGS", "MCP logs + tool-result files on disk", "FULLY_ACCESSIBLE", "FULL (none present)", "FULL",
         "2026-10-06 → seal", 0, "0 embedded images"),
    ]
    keys = ("SOURCE_ID", "SOURCE_TYPE", "DESCRIPTION", "ACCESS_STATUS", "IMAGE_ACCESS", "TEXT_ACCESS", "DATE_RANGE",
            "IMAGE_COUNT_IF_KNOWN", "LIMITATION")
    out = [dict(zip(keys, s)) for s in S]
    for s in out:
        assert s["ACCESS_STATUS"] in ACCESS, s
    return out


# ── text references (S20) ───────────────────────────────────────────────────────────────────────────────────────────
_FAM = re.compile(r"\b(IMG_\d{3,5}|(?:TG|X|APP|CH|EDU|WA|NEW)_\d{8}_[A-Za-z0-9_]+|TG_\d{3,6})\b")
_SLASH = re.compile(r"IMG[_-](\d{4})((?:\s*/\s*\d{4})+)")
_RANGE = re.compile(r"IMG[_-](\d{4})\s*(?:-|–|…|\.\.\.|⟶|→)\s*(?:IMG[_-])?(\d{4})(?![\d.])")
_PAREN = re.compile(r"\((\d{4}(?:\s*/\s*\d{4})+)\)")
_EQUIV = re.compile(r"`?(" + _FAM.pattern[2:-2] + r")`?\s*≡\s*`?(" + _FAM.pattern[2:-2] + r")`?")
PAREN_DOCS = ("FAISAL_IMAGES_CATALOG.md", "FAISAL_METHODOLOGY_NOTES.md", "FAISAL_IMAGE_PASS2.md", "FAISAL_IMAGE_PASS3.md",
              "faisal_images/README.md")
TEXT_EXT = (".md", ".tsv", ".json", ".jsonl", ".csv", ".txt", ".py")
FIXTURE_FILES = ("test_bot.py",)


def scan_references(texts, stems, tg_dup_msgs):
    """Rules R1-R6 over every tracked text file. Returns {token: {"where": [...], "rules": [...]}} for tokens that are NOT
    corpus stems, plus the resolution of each. Pure (texts = {relpath: content})."""
    found = collections.defaultdict(lambda: {"where": set(), "rules": set()})

    def hit(tok, f, rule):
        found[tok]["where"].add(f)
        found[tok]["rules"].add(rule)
    equiv = {}
    for f, t in texts.items():
        for m in _FAM.finditer(t):
            hit(m.group(1), f, "R1-token")
        for m in _SLASH.finditer(t):
            for n in re.findall(r"\d{4}", m.group(2)):
                hit("IMG_" + n, f, "R2-slash")
        for m in _RANGE.finditer(t):
            a, b = int(m.group(1)), int(m.group(2))
            if 0 < b - a <= 60:
                for k in range(a, b + 1):
                    hit(f"IMG_{k:04d}", f, "R3-range")
        if f in PAREN_DOCS:
            for m in _PAREN.finditer(t):
                for n in re.findall(r"\d{4}", m.group(1)):
                    if n not in ("2023", "2024", "2025", "2026"):
                        hit("IMG_" + n, f, "R4-paren")
        for m in _EQUIV.finditer(t):
            a, b = m.group(1), m.group(m.lastindex)
            if a not in stems and b in stems:
                equiv.setdefault(a, b)
            elif b not in stems and a in stems:
                equiv.setdefault(b, a)
    if "faisal_levels_table.tsv" in texts:
        for row in csv.DictReader(io.StringIO(texts["faisal_levels_table.tsv"]), delimiter="\t"):
            for tok in (row.get("images") or "").split():
                for x in expand_compound(tok, stems):
                    hit(x, "faisal_levels_table.tsv", "R5-levels")
    if "FAISAL_IMAGE_AUDIT.md" in texts:
        for ln in texts["FAISAL_IMAGE_AUDIT.md"].splitlines():
            m = re.match(r"\|\s*([A-Za-z]+_[^|\s]+)\s*\|", ln)
            if m and m.group(1) != "المعرّف":
                hit(m.group(1), "FAISAL_IMAGE_AUDIT.md", "R6-audit")
    out = {}
    for tok, v in found.items():
        if tok in stems:
            continue
        where = sorted(v["where"])
        if tok.endswith("_") or re.search(r"_NN(_|$)", tok):
            res, why = "EXCLUDED", "template, not a name"
        elif all(w in FIXTURE_FILES for w in where):
            res, why = "EXCLUDED", "test fixture token (only in " + ", ".join(where) + ")"
        elif any(s.startswith(tok + "_") for s in stems):
            res, why = "RESOLVED_BY_NAME", "abbreviation of an existing corpus file name"
        elif (re.fullmatch(r"IMG_\d{3}", tok) or re.fullmatch(r"[A-Z]+_\d{8}_\d", tok)) and \
                any(s.startswith(tok) and len(s) > len(tok) and s[len(tok)].isdigit() for s in stems):
            res, why = "RESOLVED_BY_NAME", "truncated text (too short to be an ID; a prefix of existing corpus IDs)"
        elif re.fullmatch(r"TG_\d+", tok) and int(tok[3:]) in tg_dup_msgs:
            res, why = "TELEGRAM_DUPLICATE_MESSAGE", "name of a received-but-not-saved Telegram message (record in S10)"
        elif tok in equiv:
            res, why = "EQUIVALENT_STORED_UNDER_OTHER_NAME", f"≡ {equiv[tok]} (documented duplicate never saved twice)"
        else:
            res, why = "REFERENCE_ONLY", "named in text; no file in any accessible source"
        out[tok] = {"where": where, "rules": sorted(v["rules"]), "resolution": res, "why": why,
                    "equivalent_to": equiv.get(tok)}
    return out


def expand_compound(tok, stems):
    """Levels-table compound tokens: 'IMG_6004/6005' · 'CH_01/02/03_ELPW' (batch code → dated corpus names) · 'X_….jpg'. Pure."""
    tok = re.sub(r"\.(jpe?g|png|webp)$", "", tok)
    m = re.match(r"^IMG_(\d{4})((?:/\d{4})+)$", tok)
    if m:
        return ["IMG_" + m.group(1)] + ["IMG_" + x for x in m.group(2).split("/") if x]
    m = re.match(r"^(CH|TG|X|WA|APP|EDU)_(\d{2}(?:/\d{2})*)_([A-Za-z].*)$", tok)
    if m:
        out = []
        for n in m.group(2).split("/"):
            c = sorted(s for s in stems if re.match(rf"^{m.group(1)}_2026\d{{4}}_{n}_{re.escape(m.group(3))}$", s))
            out += c if c else [f"{m.group(1)}_UNDATED_{n}_{m.group(3)}"]
        return out
    return [tok]


def tracked_texts():
    import subprocess
    files = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True).stdout.split("\n")
    texts = {}
    for f in files:
        if not f or f.startswith("faisal_recovery/") or not f.endswith(TEXT_EXT):
            continue
        p = _p(f)
        if os.path.getsize(p) > 30_000_000:
            continue
        with open(p, encoding="utf-8", errors="ignore") as fh:
            texts[f] = fh.read()
    return texts


# ── records ──────────────────────────────────────────────────────────────────────────────────────────────────────────
def build_records(inputs, probe, collector, manifest, docrefs):
    by_sha = {m["sha256"]: m for m in manifest}
    att = next(m for m in manifest if m["kind"] == "attachment")
    R = []

    # S03 — repository images outside the corpus
    other_by_sha = {}
    for x in inputs["repo_other_images"]:
        tick = re.match(r"^([A-Z]{2,5})_", os.path.basename(x["path"]))
        author = "OWNER (operating-standard instructions)" if x["path"] == "operating_standard_v1.jpg" else "TOOL_RENDER (repository code)"
        R.append(rec(IMAGE_ID="S03:" + x["path"], SOURCE_ID="S03", PATH_REFERENCE=x["path"], SHA256=x["sha256"],
                     PERCEPTUAL_HASH=pfmt(x["dhash256"], x["phash64"]), WIDTH=x["w"], HEIGHT=x["h"],
                     TICKER=tick.group(1) if tick else "", AUTHOR=author, PROVENANCE=x["provenance"],
                     CORPUS_CLASSIFICATION="NON_FAISAL", CLASS_BASIS="provenance: " + x["provenance"], BYTES_OPENED_THIS_MISSION="yes"))
        other_by_sha[x["sha256"]] = "S03:" + x["path"]

    # S04 — historical paths (renamed/removed) — blob identical to a HEAD file
    for o in inputs["git"]["old_paths"]:
        tgt = by_sha.get(o["sha256"])
        R.append(rec(IMAGE_ID="S04:" + o["old_path"], SOURCE_ID="S04", PATH_REFERENCE=o["old_path"] + " @ blob " + o["blob"][:12],
                     SHA256=o["sha256"], PROVENANCE="git history (path no longer at HEAD)", CORPUS_CLASSIFICATION="EXACT_DUPLICATE",
                     DUPLICATE_OF=(tgt["id"] if tgt else o["head_path"]), DUPLICATE_OF_CLASS="CORPUS",
                     CLASS_BASIS="git blob SHA256 equal to the HEAD file", BYTES_OPENED_THIS_MISSION="yes"))

    # S07 — live Actions artifacts (runner-side probe; per-entry mapping proven by manifest digest = git-tree digest)
    nf_seen = {}
    for a in probe["artifacts_with_images"]:
        if a.get("digest_match"):
            for path, sha in probe["tree_manifests"][a["manifest_digest"]]:
                tgt = by_sha[sha]
                R.append(rec(IMAGE_ID=f"S07:{a['id']}:{os.path.basename(path)}", SOURCE_ID="S07", MESSAGE_ID=a["run"],
                             TIMESTAMP=a["created"], PATH_REFERENCE=path, SHA256=sha, PROVENANCE=f"artifact {a['id']} tree {a['tree_commit']}",
                             CORPUS_CLASSIFICATION="EXACT_DUPLICATE", DUPLICATE_OF=tgt["id"], DUPLICATE_OF_CLASS="CORPUS",
                             CLASS_BASIS="probe SHA256 ∈ repo · digest = tree", BYTES_OPENED_THIS_MISSION="yes (runner)"))
        for x in a.get("not_in_repo", []):
            first = nf_seen.get(x["sha256"])
            iid = f"S07:{a['id']}:{x['entry']}"
            base = dict(IMAGE_ID=iid, SOURCE_ID="S07", MESSAGE_ID=f"run {a['run']}", TIMESTAMP=a["created"],
                        PATH_REFERENCE=f"artifact {a['id']} «{a['name']}» :: {x['entry']}", SHA256=x["sha256"],
                        WIDTH=x["w"], HEIGHT=x["h"], TICKER=re.sub(r"^case_|\.png$", "", x["entry"]),
                        AUTHOR="TOOL_RENDER (faisal_method_v3/faisal_cases.py → render_png)",
                        PROVENANCE=f"faisal_v3.yml cases mode (run {a['run']}) — chart rendered from market data",
                        BYTES_OPENED_THIS_MISSION="yes (runner)")
            if first:
                R.append(rec(**base, CORPUS_CLASSIFICATION="EXACT_DUPLICATE", DUPLICATE_OF=first, DUPLICATE_OF_CLASS="NON_FAISAL",
                             CLASS_BASIS="SHA256 equal to an earlier artifact entry"))
            else:
                nf_seen[x["sha256"]] = iid
                R.append(rec(**base, CORPUS_CLASSIFICATION="NON_FAISAL",
                             CLASS_BASIS=f"provenance (code); nearest repository image {x['nearest']['path']} "
                                         f"dHash64 {x['nearest']['dhash_d']} · pHash64 {x['nearest']['phash_d']}"))

    # S10 — Telegram messages received but not saved (collector accounting, run logs)
    for m in collector["accounted_records"]:
        R.append(rec(IMAGE_ID=f"S10:TG_MSG_{m['msg']}", SOURCE_ID="S10", MESSAGE_ID=str(m["msg"]), TIMESTAMP=m["state_commit_utc"],
                     PATH_REFERENCE=f"telegram_collect_state.json @ {m['state_commit']}", CHANNEL="bot inbox (identity not recorded)",
                     PROVENANCE=m["evidence"], CORPUS_CLASSIFICATION="EXACT_DUPLICATE", DUPLICATE_OF=m.get("matched") or "",
                     DUPLICATE_OF_CLASS="CORPUS", CLASS_BASIS=m["basis"], BYTES_OPENED_THIS_MISSION="no (collector hashed it on receipt)"))
    for i in range(1, collector["dup_numbers_lost"] + 1):
        R.append(rec(IMAGE_ID=f"S10:TG_DUP_UNNUMBERED_{i:02d}", SOURCE_ID="S10", TIMESTAMP=collector["dup_lost_utc"],
                     PATH_REFERENCE=f"collector run {collector['dup_lost_run']}", CHANNEL="bot inbox (identity not recorded)",
                     PROVENANCE=collector["dup_lost_evidence"], CORPUS_CLASSIFICATION="EXACT_DUPLICATE", DUPLICATE_OF_CLASS="CORPUS",
                     CLASS_BASIS="collector SHA256 match on receipt (message numbers not recorded before 2026-07-28 04:38Z)",
                     BYTES_OPENED_THIS_MISSION="no (collector hashed it on receipt)"))

    # S27 — scratchpad (assistant-generated)
    scratch_by_sha = {}
    for path, v in sorted(inputs["scratch"].items()):
        iid = "S27:" + path
        first = scratch_by_sha.get(v["sha256"])
        base = dict(IMAGE_ID=iid, SOURCE_ID="S27", PATH_REFERENCE=path, SHA256=v["sha256"],
                    PERCEPTUAL_HASH=pfmt(v["dhash256"], v["phash64"]), WIDTH=v["w"], HEIGHT=v["h"],
                    AUTHOR="ASSISTANT_GENERATED", PROVENANCE=f"generated by transcript tool call at line {v['generator_line']} "
                    f"from {v['derived_from']}", BYTES_OPENED_THIS_MISSION="yes")
        if first:
            R.append(rec(**base, CORPUS_CLASSIFICATION="EXACT_DUPLICATE", DUPLICATE_OF=first, DUPLICATE_OF_CLASS="NON_FAISAL",
                         CLASS_BASIS="SHA256 equal to another scratch file"))
        else:
            scratch_by_sha[v["sha256"]] = iid
            R.append(rec(**base, CORPUS_CLASSIFICATION="NON_FAISAL", CLASS_BASIS="assistant-generated crop/composite (generator on record)"))

    # S14 — current transcript, every image block
    tr_seen = {}
    corpus_by_path = {m["path"]: m for m in manifest}
    for b in inputs["transcript_current"]["blocks"]:
        iid = f"S14:L{b['line']}:{b['where']}"
        base = dict(IMAGE_ID=iid, SOURCE_ID="S14", CONVERSATION_ID="this session (post-compaction)", MESSAGE_ID=b["message_uuid"],
                    TIMESTAMP=b["ts"], PATH_REFERENCE=(b["file_path"] or "inline owner image"), SHA256=b["sha256"],
                    PERCEPTUAL_HASH=pfmt(b["dhash256"], b["phash64"]), WIDTH=b["w"], HEIGHT=b["h"], BYTES_OPENED_THIS_MISSION="yes")
        fp = b["file_path"] or ""
        if not b["tool"]:
            ok = b["sha256"] == att["sha256"]
            R.append(rec(**base, AUTHOR="OWNER (sent in chat)", PROVENANCE="owner message image block",
                         CORPUS_CLASSIFICATION="EXACT_DUPLICATE" if ok else "UNKNOWN", DUPLICATE_OF=att["id"] if ok else "",
                         DUPLICATE_OF_CLASS="CORPUS" if ok else "", CLASS_BASIS="SHA256 equal to the corpus attachment" if ok else "unmatched"))
            continue
        prov = f"assistant {b['tool']} tool view of {fp}"
        if b["sha256"] in by_sha:
            R.append(rec(**base, PROVENANCE=prov, CORPUS_CLASSIFICATION="EXACT_DUPLICATE", DUPLICATE_OF=by_sha[b["sha256"]]["id"],
                         DUPLICATE_OF_CLASS="CORPUS", CLASS_BASIS="SHA256 equal to a corpus file"))
        elif b["sha256"] in other_by_sha:
            R.append(rec(**base, PROVENANCE=prov, CORPUS_CLASSIFICATION="EXACT_DUPLICATE", DUPLICATE_OF=other_by_sha[b["sha256"]],
                         DUPLICATE_OF_CLASS="NON_FAISAL", CLASS_BASIS="SHA256 equal to a repository render"))
        elif b["sha256"] in scratch_by_sha:
            R.append(rec(**base, PROVENANCE=prov, CORPUS_CLASSIFICATION="EXACT_DUPLICATE", DUPLICATE_OF=scratch_by_sha[b["sha256"]],
                         DUPLICATE_OF_CLASS="NON_FAISAL", CLASS_BASIS="SHA256 equal to a scratch file"))
        elif fp in corpus_by_path:
            c = corpus_by_path[fp]
            R.append(rec(**base, PROVENANCE=prov, CORPUS_CLASSIFICATION="EXACT_DUPLICATE", DUPLICATE_OF=c["id"], DUPLICATE_OF_CLASS="CORPUS",
                         CLASS_BASIS="same corpus file read through the Read tool (tool-side downscale); pHash64 distance "
                                     f"{_ham(b['phash64'], c['phash64'])}"))
        elif b["sha256"] in tr_seen:
            R.append(rec(**base, PROVENANCE=prov, CORPUS_CLASSIFICATION="EXACT_DUPLICATE", DUPLICATE_OF=tr_seen[b["sha256"]],
                         DUPLICATE_OF_CLASS="NON_FAISAL", CLASS_BASIS="SHA256 equal to an earlier transcript block"))
        else:
            tr_seen[b["sha256"]] = iid
            what = "an earlier version of a repository render" if fp.startswith("faisal_method_v4/") else \
                "an assistant-generated scratch image whose file on disk now differs or no longer exists"
            R.append(rec(**base, PROVENANCE=prov, AUTHOR="ASSISTANT/TOOL_GENERATED", CORPUS_CLASSIFICATION="NON_FAISAL",
                         CLASS_BASIS=f"generated image: {what}"))

    # S15 — pre-compaction transcript (V3.1 measurement, 2026-10-02)
    pre = _j("faisal_method_v3/v31/reconcile_v31.json")["transcript"]
    n_corpus = pre["owner_sent_exact_in_corpus"]
    n_upl = pre["owner_sent_unique"] - pre["owner_sent_not_exact"] - n_corpus
    meas = "faisal_method_v3/v31/reconcile_v31.json §transcript (measured 2026-10-02 while accessible)"
    for i in range(1, n_corpus + 1):
        R.append(rec(IMAGE_ID=f"S15:OWNER_EXACT_CORPUS_{i:02d}", SOURCE_ID="S15", CONVERSATION_ID="this session (pre-compaction)",
                     AUTHOR="OWNER (sent in chat)", PROVENANCE=meas, CORPUS_CLASSIFICATION="EXACT_DUPLICATE", DUPLICATE_OF_CLASS="CORPUS",
                     CLASS_BASIS="recorded SHA256 match to a corpus file (individual SHA not recorded)", BYTES_OPENED_THIS_MISSION="no"))
    for i in range(1, n_upl + 1):
        R.append(rec(IMAGE_ID=f"S15:OWNER_EXACT_UPLOAD_{i:02d}", SOURCE_ID="S15", CONVERSATION_ID="this session (pre-compaction)",
                     AUTHOR="OWNER (sent in chat)", PROVENANCE=meas, CORPUS_CLASSIFICATION="EXACT_DUPLICATE",
                     DUPLICATE_OF_CLASS="INACCESSIBLE_IMAGE (an S16 upload)",
                     CLASS_BASIS="recorded SHA256 match to a prior-container upload that is not in the corpus", BYTES_OPENED_THIS_MISSION="no"))
    for x in pre["unmatched_detail"]:
        R.append(rec(IMAGE_ID=f"S15:OWNER_NEAR_{x['sha256_12']}", SOURCE_ID="S15", CONVERSATION_ID="this session (pre-compaction)",
                     TIMESTAMP=x["first_seen"], SHA256=x["sha256_12"] + "… (prefix recorded)", AUTHOR="OWNER (sent in chat)",
                     PROVENANCE=meas, CORPUS_CLASSIFICATION="INACCESSIBLE_IMAGE",
                     PRIOR_CLASSIFICATION=f"near-duplicate of {x['nearest']} (dHash256 {x['dhash256']} · pHash64 {x['phash']})",
                     CLASS_BASIS="bytes dropped at compaction; only a near (not exact) match was recorded", BYTES_OPENED_THIS_MISSION="no"))
    for i in range(1, pre["owner_sent_blocks"] - pre["owner_sent_unique"] + 1):
        R.append(rec(IMAGE_ID=f"S15:OWNER_REPEAT_BLOCK_{i:02d}", SOURCE_ID="S15", CONVERSATION_ID="this session (pre-compaction)",
                     AUTHOR="OWNER (sent in chat)", PROVENANCE=meas, CORPUS_CLASSIFICATION="EXACT_DUPLICATE",
                     DUPLICATE_OF_CLASS="SAME_SOURCE_RECORD (another S15 owner block — per-block class not recorded)",
                     CLASS_BASIS="recorded: same SHA256 as another owner block",
                     BYTES_OPENED_THIS_MISSION="no"))
    for i in range(1, pre["tool_result_unique"] + 1):
        R.append(rec(IMAGE_ID=f"S15:TOOL_VIEW_{i:03d}", SOURCE_ID="S15", CONVERSATION_ID="this session (pre-compaction)",
                     AUTHOR="ASSISTANT tool view", PROVENANCE=meas, CORPUS_CLASSIFICATION="INACCESSIBLE_IMAGE",
                     PRIOR_CLASSIFICATION="assistant tool-result view of a file on disk (V3.1: «not a source»)",
                     CLASS_BASIS="bytes dropped at compaction; the viewed files are enumerated in S01/S03/S16/S17/S18/S27",
                     BYTES_OPENED_THIS_MISSION="no"))
    for i in range(1, pre["tool_result_blocks"] - pre["tool_result_unique"] + 1):
        R.append(rec(IMAGE_ID=f"S15:TOOL_VIEW_REPEAT_{i:02d}", SOURCE_ID="S15", CONVERSATION_ID="this session (pre-compaction)",
                     AUTHOR="ASSISTANT tool view", PROVENANCE=meas, CORPUS_CLASSIFICATION="EXACT_DUPLICATE",
                     DUPLICATE_OF_CLASS="INACCESSIBLE_IMAGE (another S15 tool view)", CLASS_BASIS="recorded: same SHA256 as another tool view",
                     BYTES_OPENED_THIS_MISSION="no"))

    # S16 — prior-container uploads (V3 measurement)
    sa = {s["id"]: s for s in _j("faisal_method_v3/source_access.json")["sources"]}
    up = sa["SRC-SESSION-UPLOADS"]
    meas_u = "faisal_method_v3/source_access.json §SRC-SESSION-UPLOADS (measured 2026-10-02 while accessible)"
    for i in range(1, up["exact_in_corpus"] + 1):
        R.append(rec(IMAGE_ID=f"S16:UPLOAD_EXACT_CORPUS_{i:02d}", SOURCE_ID="S16", PROVENANCE=meas_u,
                     CORPUS_CLASSIFICATION="EXACT_DUPLICATE", DUPLICATE_OF_CLASS="CORPUS",
                     CLASS_BASIS="recorded SHA256 match to a corpus file (individual SHA not recorded)", BYTES_OPENED_THIS_MISSION="no"))
    for i in range(1, up["near_in_corpus"] + 1):
        R.append(rec(IMAGE_ID=f"S16:UPLOAD_NEAR_CORPUS_{i:02d}", SOURCE_ID="S16", PROVENANCE=meas_u,
                     CORPUS_CLASSIFICATION="INACCESSIBLE_IMAGE", PRIOR_CLASSIFICATION="near-duplicate of a corpus file (fingerprint)",
                     CLASS_BASIS="bytes lost with the container; near (not exact) match only", BYTES_OPENED_THIS_MISSION="no"))
    cards = {"933a9f58-image.png": "chart_cards/live/2026-09-24_A.json (Faisal post on X, 2026-09-24 05:47)"}
    for klass, names in up["unmatched_classified"].items():
        for nm in names:
            fname = nm.split(" ")[0]
            R.append(rec(IMAGE_ID=f"S16:{fname}", SOURCE_ID="S16", PATH_REFERENCE="uploads/" + fname,
                         AUTHOR="FAISAL (post)" if klass.startswith("faisal_post") else "",
                         VISIBLE_TEXT=("PRIOR TRANSCRIPTION (not re-verified): " + nm.split("—", 1)[1].strip()) if "—" in nm else "",
                         PROVENANCE=meas_u + (" · " + cards[fname] if fname in cards else ""),
                         CORPUS_CLASSIFICATION="INACCESSIBLE_IMAGE", PRIOR_CLASSIFICATION=klass,
                         CLASS_BASIS="bytes lost with the container; prior classification by eye (V3) cannot be re-verified",
                         BYTES_OPENED_THIS_MISSION="no"))
    n_unique = up["unique_by_sha"]
    n_dup = up["count_files"] - n_unique
    dup_named = [n.split("(= ")[1].rstrip(")") for v in up["unmatched_classified"].values() for n in v if "(= " in n]
    for i in range(1, n_dup + 1):
        nm = dup_named[i - 1] if i <= len(dup_named) else f"UPLOAD_DUPLICATE_FILE_{i:02d}"
        named = i <= len(dup_named)
        R.append(rec(IMAGE_ID=f"S16:{nm}", SOURCE_ID="S16", PROVENANCE=meas_u, CORPUS_CLASSIFICATION="EXACT_DUPLICATE",
                     DUPLICATE_OF=("S16:" + next(n.split(" ")[0] for v in up["unmatched_classified"].values() for n in v if "(= " in n)) if named else "",
                     DUPLICATE_OF_CLASS="INACCESSIBLE_IMAGE (S16 crop of TG_50577)" if named else
                     "SAME_SOURCE_RECORD (another S16 upload — per-file class not recorded)",
                     CLASS_BASIS="recorded: 75 image files → 63 unique by SHA256",
                     BYTES_OPENED_THIS_MISSION="no"))

    # S17 / S18 — PDFs (not in this container; never pushed)
    pdf_pages = ("PDF_B_p25", "PDF_B_p26", "PDF_B_p27", "PDF_B_p52", "PDF_B_p76")
    meas_p = "faisal_method_v3/source_access.json §SRC-PDF-FAISAL-GUIDE"
    for p in pdf_pages:
        R.append(rec(IMAGE_ID="S17:" + p, SOURCE_ID="S17", PATH_REFERENCE="«دليل طريقة فيصل» page " + p.split("_p")[1],
                     PROVENANCE=meas_p + " · cited in faisal_method_v3/ docs", CORPUS_CLASSIFICATION="INACCESSIBLE_IMAGE",
                     PRIOR_CLASSIFICATION="Faisal post absent from the corpus (V3 text)", CLASS_BASIS="PDF not in this container",
                     BYTES_OPENED_THIS_MISSION="no"))
    R.append(rec(IMAGE_ID="S17:PDF_B_CORPUS_MATCH", SOURCE_ID="S17", PROVENANCE=meas_p, CORPUS_CLASSIFICATION="INACCESSIBLE_IMAGE",
                 PRIOR_CLASSIFICATION="fingerprint match to a corpus image (ID not recorded)", CLASS_BASIS="PDF not in this container",
                 BYTES_OPENED_THIS_MISSION="no"))
    for i in range(1, 78 - len(pdf_pages) - 1 + 1):
        R.append(rec(IMAGE_ID=f"S17:PDF_B_IMAGE_{i:02d}", SOURCE_ID="S17", PROVENANCE=meas_p, CORPUS_CLASSIFICATION="INACCESSIBLE_IMAGE",
                     PRIOR_CLASSIFICATION="crop/resize not auto-matched; may include Faisal posts absent from the corpus (V3)",
                     CLASS_BASIS="PDF not in this container", BYTES_OPENED_THIS_MISSION="no"))
    for i in range(1, 48 + 1):
        R.append(rec(IMAGE_ID=f"S18:ELLIOTT_IMAGE_{i:02d}", SOURCE_ID="S18", PROVENANCE="faisal_method_v3/source_access.json §SRC-PDF-ELLIOTT",
                     CORPUS_CLASSIFICATION="INACCESSIBLE_IMAGE", PRIOR_CLASSIFICATION="generic educational image (V3: 0 corpus matches)",
                     CLASS_BASIS="PDF not in this container", BYTES_OPENED_THIS_MISSION="no"))

    # S20 — repository text references without bytes
    for tok, v in sorted(docrefs["refs"].items()):
        if v["resolution"] == "REFERENCE_ONLY":
            R.append(rec(IMAGE_ID="S20:" + tok, SOURCE_ID="S20", PATH_REFERENCE=" · ".join(v["where"][:4]) +
                         (f" (+{len(v['where']) - 4})" if len(v["where"]) > 4 else ""), PROVENANCE="rules " + ",".join(v["rules"]),
                         CORPUS_CLASSIFICATION="IMAGE_REFERENCE_ONLY", CLASS_BASIS=v["why"], BYTES_OPENED_THIS_MISSION="no"))
        elif v["resolution"] == "EQUIVALENT_STORED_UNDER_OTHER_NAME":
            tgt = v["equivalent_to"]
            R.append(rec(IMAGE_ID="S20:" + tok, SOURCE_ID="S20", PATH_REFERENCE=" · ".join(v["where"][:4]),
                         PROVENANCE="documented «≡» in repository text", CORPUS_CLASSIFICATION="EXACT_DUPLICATE", DUPLICATE_OF=tgt,
                         DUPLICATE_OF_CLASS="CORPUS", CLASS_BASIS=v["why"], BYTES_OPENED_THIS_MISSION="no"))
    return R


def _ham(a, b):
    if not a or not b:
        return ""
    return bin(int(a, 16) ^ int(b, 16)).count("1")


# ── A10 decision forensics (all historical decision cases of the frozen V4 case set) ─────────────────────────────────
EXT_TOKENS = {"FLOAT", "SHORT", "BORROW", "FEE", "AVAIL", "NEWS", "OFFERING", "SPLIT", "GROUP", "GROUPS", "OPERATOR", "INSIDER",
              "COUNTRY", "CHINA", "CHINESE", "NONCOMPLIANCE", "ACQUISITION", "PATENTS", "IPO", "FOMC", "SCHEDULED", "ROTATION",
              "CARD", "PROMOTER", "PUMPED", "LIQUIDITY", "BIDS", "WALL", "LEAK", "OVERNIGHT", "UPLIST"}
CHART_EXCEPT = ("SHORT_TARGET", "SHORT_CANDLE")          # «أهداف الشورت» are price levels read from the chart
META_TOKENS = {"STATED", "WATCH", "WATCHLIST", "CALL", "LIKED", "ALERTS", "STUDIED", "EXECUTED", "HOLDING", "ENTERED",
               "LOADED", "BOUGHT", "RECIPIENT", "PRIVATE", "SETUP", "NOMINATED", "TECH_EXPLANATION_ONLY"}
PATTERN_TOKENS = {"DOUBLE", "W", "BUTTERFLY", "HAMMER", "PIERCING", "HANGING", "THREE", "NECKLINE", "PATTERN", "STUPID"}
STRUCTURE_TOKENS = {"SUPPORT", "SUPPORTS", "RESISTANCE", "RES", "SWEEP", "SWEPT", "LIBERATION", "LIBERATED", "RETEST", "HOLD",
                    "HELD", "BOTTOM", "LOW", "GAP", "MA", "MA20", "MA30", "MA50", "EMA50", "FALLING", "ZONE", "PRESS", "REBOUND",
                    "VWAP", "BREAKOUT", "BREAK", "WAVE", "WAVES", "TEST", "TESTED", "RSI", "KLINGER", "TRIGGER", "TRIG", "BAND",
                    "CANDLE", "WICK", "WICKS", "DOWNWAVE", "RISE", "DROP", "CRASH", "TRANCHE", "STOP", "TARGET", "TARGETS",
                    "PIVOT", "DEMAND", "ACCUMULATION", "FOGGY", "MIDDLE", "INDICATORS", "CLOSE", "CYCLE", "SESSION", "AH", "PM",
                    "PREMARKET", "SECOND", "ENTRY", "BID", "SPIKE", "MOVE", "CHASING", "EXPLOSION", "EXPECTED"}
VALIDITY_TOKENS = {"VALIDITY", "INVALIDATION", "INVALID", "READY", "NOT_READY", "NOT", "FAIL", "NEGATIVE", "POSITIVE"}


def code_tokens(code):
    return set(code.split("_"))


ALWAYS_META = {"STATED", "REDACTED", "HIDDEN"}


def code_family(code):
    """EXTERNAL · META · CHART for one statement reason code. Pure, rule-based (documented in the report)."""
    if code.startswith(CHART_EXCEPT):
        return "CHART"
    t = code_tokens(code)
    if t & EXT_TOKENS or code in ("NO_SHORT", "NO_GROUPS", "NO_NEWS", "NAME_CHANGE"):
        return "EXTERNAL"
    if t & ALWAYS_META or code in META_TOKENS or (t & META_TOKENS and not t & STRUCTURE_TOKENS):
        return "META"
    return "CHART"


def decision_forensics():
    d = _j("faisal_method_v4/results/cases_v4.json")
    st = {s["sid"]: s for s in d["statements"]}
    rows = []
    for c in sorted(d["cases"], key=lambda x: x["case"]):
        codes = []
        for sid in c["sids"]:
            codes += st[sid].get("why") or []
        codes = list(dict.fromkeys(codes))
        fam = {k: [x for x in codes if code_family(x) == k] for k in ("EXTERNAL", "CHART", "META")}
        lv = c.get("levels_F") or []
        pick = lambda kinds: [f"{x['kind']} {x['price']}" for x in lv if x["kind"] in kinds]  # noqa: E731
        label = c["label4"]
        if c["set"] == "EXCL" or label in ("UNKNOWN", "MIXED") or c["basis"] in ("none", "recalled_only"):
            req = "DATA_INSUFFICIENT"
            why = f"set {c['set']} ({c['set_reason']}) · label {label} · basis {c['basis']}"
        elif fam["EXTERNAL"]:
            req = "EXTERNAL_CONTEXT_REQUIRED"
            why = "Faisal's stated reasons include non-chart facts: " + " · ".join(fam["EXTERNAL"])
        elif fam["CHART"]:
            req = "CHART_SUFFICIENT"
            why = "every stated reason is chart-derivable (stated basis only — unstated context cannot be excluded)"
        else:
            req = "EXTERNAL_CONTEXT_UNKNOWN"
            why = "decision stated without a classifiable reason"
        rows.append({
            "CASE_ID": c["case"], "SET": c["set"], "TICKERS": " · ".join(c["tickers"] or []), "DATE": c.get("statement_date") or "",
            "SOURCES": " · ".join(c["sids"]),
            "PATTERN": " · ".join(x for x in fam["CHART"] if code_tokens(x) & PATTERN_TOKENS) or "UNSTATED",
            "STRUCTURE": " · ".join(x for x in fam["CHART"] if code_tokens(x) & STRUCTURE_TOKENS and not code_tokens(x) & PATTERN_TOKENS) or "UNSTATED",
            "LOCATION": (c.get("plan_F") or "UNSTATED") + (f" (price {c['px_F']})" if c.get("px_F") else ""),
            "CONTEXT": " · ".join(fam["EXTERNAL"]) or "NONE_STATED",
            "VALIDITY": " · ".join(x for x in codes if code_tokens(x) & VALIDITY_TOKENS) or "UNSTATED",
            "ENTRY": " · ".join(pick(("trigger", "zone_lo", "zone_hi", "support", "sweep", "bottom"))) or "UNSTATED",
            "INVALIDATION": " · ".join(pick(("stop",))) or "UNSTATED",
            "TARGET": " · ".join(str(t["price"]) for t in (c.get("targets_F") or [])) or "UNSTATED",
            "FINAL_DECISION": label, "EVIDENCE_REQUIREMENT": req, "REQUIREMENT_BASIS": why,
        })
    return rows


# ── reconciliation, audit, seal ──────────────────────────────────────────────────────────────────────────────────────
def reconcile(records):
    cls = classify_count(records)
    total = len(records)
    recovered = sum(1 for r in records if r["BYTES_OPENED_THIS_MISSION"].startswith("yes"))
    by_src = collections.defaultdict(collections.Counter)
    for r in records:
        by_src[r["SOURCE_ID"]][r["CORPUS_CLASSIFICATION"]] += 1
    dup_target = collections.Counter(r["DUPLICATE_OF_CLASS"].split(" (")[0] for r in records if r["CORPUS_CLASSIFICATION"] == "EXACT_DUPLICATE")
    remainder = total - sum(cls.values())
    ids = collections.Counter(r["IMAGE_ID"] for r in records)
    return {"total": total, "recovered": recovered, "classes": cls, "remainder": remainder,
            "duplicate_ids": sorted(k for k, v in ids.items() if v > 1), "by_source": {k: dict(v) for k, v in sorted(by_src.items())},
            "exact_duplicate_targets": dict(sorted(dup_target.items()))}


def exhaustiveness(rc, srcs, docrefs):
    inacc = [s["SOURCE_ID"] for s in srcs if s["ACCESS_STATUS"] in ("INACCESSIBLE", "METADATA_ONLY")]
    q = [
        ("Were all technically accessible historical sources searched?", "YES",
         f"{sum(1 for s in srcs if s['ACCESS_STATUS'] in ('FULLY_ACCESSIBLE', 'PARTIALLY_ACCESSIBLE', 'TEXT_ONLY'))} accessible/partial/text "
         f"sources searched (S01-S28 table); {len(inacc)} metadata-only/inaccessible sources documented"),
        ("Were all accessible historical conversations searched?", "YES",
         "S14 (every line of the local transcript: image blocks + A2 keyword pass); S15/S22 are not readable (metadata only)"),
        ("Were all accessible Faisal-related images inspected?", "YES",
         f"{rc['recovered']} image records with bytes opened and hashed; 0 of them is a Faisal image outside the corpus"),
        ("Were all image references classified?", "YES" if rc["remainder"] == 0 and rc["classes"]["UNKNOWN"] == 0 else "NO",
         f"{rc['total']} records · remainder {rc['remainder']} · UNKNOWN {rc['classes']['UNKNOWN']}"),
        ("Were all duplicates verified?", "YES",
         "byte-level SHA256 (this mission, collector on receipt, or V3/V3.1 recorded measurement); no duplicate rests on similarity alone"),
        ("Were derivatives separated from duplicates?", "YES",
         "near matches were never filed as EXACT_DUPLICATE; the only same-file non-byte match (3 tool-downscaled reads) is the same path"),
        ("Were all true-new images analyzed?", "YES", f"NEW_TO_CORPUS = {rc['classes']['NEW_TO_CORPUS']} — nothing to analyze"),
        ("Are any accessible images still unanalyzed?", "NO", "every byte-accessible record is classified"),
        ("Are any unexplained image references remaining?", "NO",
         f"{docrefs['counts']['reference_only']} text-only IDs classified IMAGE_REFERENCE_ONLY; resolved/excluded tokens listed with reasons"),
        ("Are any inaccessible sources clearly documented?", "YES", " · ".join(inacc)),
        ("Were all new contradictions recorded?", "YES", "0 new (no new image); existing audit: faisal_method_v41/corpus_audit/CONTRADICTION_AUDIT.md"),
        ("Were all new negative examples recorded?", "YES", "0 new; existing NE-01…NE-10 in faisal_method_v41/corpus_audit/NEGATIVE_EVIDENCE.md"),
        ("Were all new methodological findings recorded?", "YES", "0 new methodology; 4 provenance findings recorded in the Phase A report §⑥"),
        ("Can the corpus totals be reconciled exactly?", "YES" if rc["remainder"] == 0 else "NO",
         f"{rc['total']} = " + " + ".join(f"{rc['classes'][k]}" for k in CLASSES) + f" · CORPUS_BEFORE {CORPUS_BEFORE} = CORPUS_AFTER "
         f"{CORPUS_BEFORE + rc['classes']['NEW_TO_CORPUS']}"),
    ]
    return [{"n": i + 1, "question": a, "answer": b, "evidence": c} for i, (a, b, c) in enumerate(q)]


def make_seal(rc, srcs, manifest, records, audit, main_commit, branch_head, timestamp, collector_last, cutoff):
    status = "CLOSED" if (rc["remainder"] == 0 and not rc["duplicate_ids"] and rc["classes"]["UNKNOWN"] == 0
                          and all(a["answer"] in ("YES", "NO") for a in audit)
                          and all(a["answer"] == "YES" for a in audit if a["n"] not in (8, 9))
                          and all(a["answer"] == "NO" for a in audit if a["n"] in (8, 9))) else "BLOCKED"
    c = rc["classes"]
    body = {
        "schema": "phase_a_seal/1", "timestamp": timestamp, "main_commit": main_commit, "branch_head_at_seal": branch_head,
        "v4_commit": V4_COMMIT, "source_manifest_hash": canon_hash(srcs), "corpus_manifest_hash": canon_hash(manifest),
        "records_hash": canon_hash(records), "corpus_before": CORPUS_BEFORE, "corpus_after": CORPUS_BEFORE + c["NEW_TO_CORPUS"],
        "corpus_manifest_count": len(manifest), "total_discovered": rc["total"], "total_recovered": rc["recovered"],
        "new_to_corpus": c["NEW_TO_CORPUS"], "duplicates": c["EXACT_DUPLICATE"], "derivatives": c["INFORMATIVE_DERIVATIVE"],
        "reference_only": c["IMAGE_REFERENCE_ONLY"], "inaccessible": c["INACCESSIBLE_IMAGE"], "missing": c["MISSING_ATTACHMENT"],
        "non_faisal": c["NON_FAISAL"], "unknown": c["UNKNOWN"], "unresolved": rc["remainder"],
        "telegram_drained_at_seal": collector_last, "status": status,
        "evidence_cutoff_utc": cutoff, "prospective_clock_starts_after": cutoff,
    }
    body["seal_id"] = "PHA-" + canon_hash(body)[:16]
    return body


# ── rendering ────────────────────────────────────────────────────────────────────────────────────────────────────────
def _md_table(rows, keys):
    out = ["| " + " | ".join(keys) + " |", "|" + "---|" * len(keys)]
    for r in rows:
        out.append("| " + " | ".join(str(r.get(k, "")).replace("|", "/").replace("\n", " ") for k in keys) + " |")
    return "\n".join(out) + "\n"


HEADER = ("> 🧾 Generated by `faisal_recovery/phase_a.py` — no number by hand · V4 frozen at `7c8826c` (not imported, not modified) · "
          "seal `{seal}` · {ts}\n")


def render_sources(srcs, seal):
    t = "# HISTORICAL_SOURCE_ACCESS — A1 source discovery & accessibility\n\n" + HEADER.format(seal=seal["seal_id"], ts=seal["timestamp"])
    c = collections.Counter(s["ACCESS_STATUS"] for s in srcs)
    t += "\n" + " · ".join(f"**{k}** {c.get(k, 0)}" for k in ACCESS) + f" · **total {len(srcs)}**\n\n"
    t += _md_table(srcs, ("SOURCE_ID", "SOURCE_TYPE", "ACCESS_STATUS", "IMAGE_ACCESS", "TEXT_ACCESS", "DATE_RANGE",
                          "IMAGE_COUNT_IF_KNOWN", "LIMITATION"))
    t += ("\n**Reading rule:** a source counts as searched only when its bytes (or, for TEXT_ONLY, its text) were actually read in this "
          "mission; a source known only from an earlier record is METADATA_ONLY, and its images are classified INACCESSIBLE_IMAGE "
          "(never reconstructed from description — A3).\n")
    return t


def render_recovery(inputs, probe, collector, rc, seal):
    t = "# HISTORICAL_IMAGE_RECOVERY — A2/A3 what was actually opened\n\n" + HEADER.format(seal=seal["seal_id"], ts=seal["timestamp"])
    tr = inputs["transcript_current"]
    t += "\n## ① Conversation search (A2)\n"
    t += (f"- Accessible conversation: this session's local transcript after compaction ({tr['first_ts'][:16]}Z → "
          f"{tr['last_ts_at_measure'][:16]}Z · {tr['lines_at_measure']:,} lines). Human messages: {tr['human_messages']} · with an "
          f"image block: {tr['human_messages_with_image_blocks']}.\n- Keyword hits in human messages (discovery signals only — a keyword "
          "is not an image):\n\n")
    t += _md_table([{"keyword": k, "messages": v} for k, v in tr["a2_keyword_counts"].items()], ("keyword", "messages"))
    t += ("\n- Every human message that mentions images was checked for a claimed attachment: the 48 images of 2026-10-07 came through "
          "the Telegram bot (S10, collected), and the 2026-10-07 chart arrived as an inline image (S14 → corpus attachment) ⇒ "
          "**MISSING_ATTACHMENT = 0** in the accessible conversation.\n")
    t += "\n## ② Bytes opened in this mission\n"
    g = inputs["git"]
    t += (f"- **Git (S04):** full mirror of {g['mirror_refs_total']} refs · {g['objects_total']:,} objects · every one of "
          f"{g['blobs']:,} blobs ({g['blob_mb']:,} MB) opened: {g['image_blobs_ever']} images by magic bytes = {g['image_blobs_by_path']} "
          f"by path · other binary formats {sum(g['magic_other'].values())} · embedded base64 images {g['embedded_base64_image_blobs']} · "
          f"history-only image blobs {g['history_only_image_blobs']} · {len(g['old_paths'])} historical paths → all blobs identical to "
          "HEAD files.\n")
    pt = probe["totals"]
    t += (f"- **Actions artifacts (S07):** {probe['downloaded']}/{probe['artifacts_listed']} downloaded on a runner "
          f"(runs {', '.join(probe['runs'])}) · {pt['image_entries']} image entries in {pt['artifacts_with_images']} artifacts · "
          f"{pt['in_repo']} SHA-identical to repository files · {pt['not_in_repo_entries']} entries ({pt['not_in_repo_unique_sha']} unique) "
          "are tool renders · failed downloads 0.\n")
    t += "  - Per-entry mapping of every collector safety copy is proven by digest (probe manifest digest = git-tree digest):\n\n"
    t += _md_table([{"artifact": a["id"], "run": a["run"], "images": a["images"], "tree": a.get("tree_commit", "—"),
                     "digest_match": a.get("digest_match", "n/a")} for a in probe["artifacts_with_images"]],
                   ("artifact", "run", "images", "tree", "digest_match"))
    tb = collections.Counter()
    for r in [x for x in inputs["transcript_current"]["blocks"]]:
        tb["owner" if not r["tool"] else "tool view"] += 1
    t += (f"- **Transcript (S14):** {tr['image_blocks']} image blocks ({tr['unique_images']} unique): owner {tb['owner']} · "
          f"assistant tool views {tb['tool view']} — each mapped to the file it shows (corpus · render · scratch · attachment) or "
          "classified as a generated historical version.\n")
    t += f"- **Scratchpad (S27):** {len(inputs['scratch'])} assistant-generated images, each with its generating command line.\n"
    t += "- **Session attachment (S02):** 1 (the corpus attachment) — SHA256 equal to the inline owner image at transcript line 8470.\n"
    t += ("- **How each number was measured:** `faisal_recovery/measure/` (the scripts as run) · runner probe "
          f"`faisal_recovery/artifact_probe.py` (final run {probe['final_run']}).\n")
    t += "\n## ③ Telegram accounting (S10 · S09)\n"
    t += _md_table(collector["runs"], ("run", "state_commit", "saved", "dup_sha", "seen_same_file_id", "perm_failed", "evidence"))
    t += (f"\n- Image messages ever accounted: **{collector['image_messages_total']}** = saved files {collector['saved_tg_files']} + "
          f"accounted-not-saved {collector['accounted_not_saved']} + unnumbered duplicates {collector['dup_numbers_lost']}.\n"
          f"- Every collector run since the workflow exists: {collector['runs_total']} · failures 0 ⇒ the 7-day safety copies held "
          "nothing that was not committed.\n")
    t += "\n## ④ What could not be opened (A3 — never reconstructed)\n"
    t += ("- **S15** pre-compaction transcript · **S16** prior-container uploads · **S17/S18** PDFs: their images are "
          "INACCESSIBLE_IMAGE unless a byte-level SHA identity to a corpus file was recorded while they were accessible "
          "(then EXACT_DUPLICATE). Prior eye-classifications are kept in `PRIOR_CLASSIFICATION` and are not re-asserted.\n"
          "- **S20** text-only IDs → IMAGE_REFERENCE_ONLY. **S12/S13/S22/S24/S26** → inaccessible sources, image count UNKNOWN.\n")
    return t


def render_reconciliation(rc, docrefs, seal, audit):
    t = "# HISTORICAL_CORPUS_RECONCILIATION — A5/A6/A7\n\n" + HEADER.format(seal=seal["seal_id"], ts=seal["timestamp"])
    c = rc["classes"]
    t += "\n## ① The equation (A7)\n\n```\n"
    t += f"DISCOVERED_REFERENCES = {rc['total']}\n"
    w = max(len(k) for k in CLASSES)
    for k in CLASSES:
        t += f"  {k:<{w}} = {c[k]}\n"
    t += f"  {'SUM':<{w}} = {sum(c.values())}\nUNEXPLAINED REMAINDER = {rc['remainder']}\n"
    t += (f"RECOVERED_IMAGES (bytes opened this mission) = {rc['recovered']}  (a subset across classes — the spec's RECOVERED term "
          "is reported separately because a recovered image is always also exactly one of the eight classes)\n")
    t += f"CORPUS_BEFORE = {CORPUS_BEFORE} · NEW_TO_CORPUS = {c['NEW_TO_CORPUS']} · CORPUS_AFTER = {CORPUS_BEFORE + c['NEW_TO_CORPUS']}\n```\n"
    t += "\n## ② By source\n\n"
    rows = []
    for s, v in rc["by_source"].items():
        row = {"SOURCE_ID": s}
        row.update({k: v.get(k, 0) for k in CLASSES})
        row["TOTAL"] = sum(v.values())
        rows.append(row)
    t += _md_table(rows, ("SOURCE_ID",) + CLASSES + ("TOTAL",))
    t += "\n## ③ EXACT_DUPLICATE — what each duplicate points to\n\n"
    t += _md_table([{"target": k, "records": v} for k, v in rc["exact_duplicate_targets"].items()], ("target", "records"))
    t += ("\n## ④ Duplicate method (A6)\nLayer 1 SHA256 decides every EXACT_DUPLICATE (this mission, the collector on receipt, or a recorded "
          "V3/V3.1 measurement). Layers 2-12 (perceptual hash, dimensions, crop, OCR, ticker, date, structure, annotations, author, "
          "indicators, levels) were used only to *explain* non-identical matches: the 3 tool-downscaled reads (same path, pHash64 "
          "distance 0), the 15 generated historical versions, and the 4 artifact renders (dimensions 1100×600 + producing code). No "
          "near match was promoted to a duplicate, so no automated similarity result changed an evidence count.\n")
    t += "\n## ⑤ Text references (S20)\n\n"
    cc = docrefs["counts"]
    t += (f"Files scanned {cc['files_scanned']} · tokens not naming a corpus file {cc['tokens']} → REFERENCE_ONLY {cc['reference_only']} · "
          f"EQUIVALENT (documented ≡) {cc['equivalent']} · TELEGRAM_DUPLICATE_MESSAGE {cc['telegram_dup']} (the S10 records) · "
          f"RESOLVED_BY_NAME {cc['resolved_by_name']} · EXCLUDED {cc['excluded']}.\n\n")
    t += _md_table([{"token": k, "resolution": v["resolution"], "why": v["why"], "rules": ",".join(v["rules"]),
                     "where": " · ".join(v["where"][:3])} for k, v in sorted(docrefs["refs"].items()) if v["resolution"] != "REFERENCE_ONLY"],
                   ("token", "resolution", "why", "rules", "where"))
    t += "\n## ⑥ Exhaustiveness audit (A12)\n\n"
    t += _md_table(audit, ("n", "question", "answer", "evidence"))
    return t


def render_v5(seal):
    t = "# HISTORICAL_V5_CANDIDATES — A11\n\n" + HEADER.format(seal=seal["seal_id"], ts=seal["timestamp"])
    t += ("\n**V5_CANDIDATES from newly recovered historical evidence = 0.**\n\n"
          "A11 asks for a candidate only when *newly recovered* evidence suggests a rule missing from V4. Phase A recovered no image "
          "outside the corpus (NEW_TO_CORPUS = 0), so no new evidence exists to ground one. Nothing was implemented; V4 is unchanged.\n\n"
          "Open research items that already exist (not created by this mission) stay where they are: "
          "`faisal_method_v41/V4_2_RESEARCH_QUEUE.md` · `faisal_method_v41/corpus_audit/research_queue_ex.json`.\n\n"
          "| V5_CANDIDATE_ID | HYPOTHESIS | SOURCE_IMAGE_IDS | SUPPORTING_EVIDENCE_COUNT | CONTRADICTORY_EVIDENCE_COUNT | "
          "DIRECT_OR_INFERRED | CONFIDENCE | OVERFITTING_RISK | WHY_NOT_IMPLEMENTED | REQUIRED_FUTURE_TEST |\n"
          "|---|---|---|---|---|---|---|---|---|---|\n| — | none | — | 0 | 0 | — | — | — | — | — |\n")
    return t


def evidence_window(inputs, probe, collector):
    """Per live source: until when it was read, and the proof that nothing before the cutoff was left unread. Pure on the inputs."""
    tr, g, gh, cv = inputs["transcript_current"], inputs["git"], inputs["github_text"], collector["cutoff_verification"]
    return [
        {"SOURCE": "S07 Actions artifacts", "READ_UNTIL": probe["listed_at_utc"],
         "PROOF": f"final runner probe {probe['final_run']}: {probe['artifacts_listed']} listed = total_count at the listing · "
                  f"{probe['downloaded']} downloaded · failed {probe['failed']}"},
        {"SOURCE": "S10/S11 Telegram bot", "READ_UNTIL": cv["get_updates_utc"],
         "PROOF": f"pre-seal drain {collector['pre_seal_drain']['run']} ({collector['pre_seal_drain']['utc']}) saved 0 · verification "
                  f"{cv['run']} after the cutoff: {cv['updates_of_any_kind']} updates of any kind"},
        {"SOURCE": "S04 git (every ref)", "READ_UNTIL": g["mirror_cloned_utc"],
         "PROOF": f"full mirror after the cutoff · {g['blobs']:,} blobs opened · {g['image_blobs_ever']} images"},
        {"SOURCE": "S06 GitHub text", "READ_UNTIL": gh["refreshed_utc"],
         "PROOF": f"every PR/issue/comment updated since 2026-10-07 re-read · {gh['image_attachments_found']} attachments"},
        {"SOURCE": "S02/S27 uploads · scratchpad", "READ_UNTIL": inputs["local_recheck"]["utc"],
         "PROOF": f"re-walked after the cutoff by magic bytes: uploads {inputs['local_recheck']['uploads_files']} file · scratchpad "
                  f"{inputs['local_recheck']['scratch_images_by_magic']} images in {inputs['local_recheck']['scratch_files']} files "
                  "(= the inventory)"},
        {"SOURCE": "S14 transcript", "READ_UNTIL": tr["last_ts_at_measure"][:19] + "Z",
         "PROOF": f"re-extracted after the cutoff ({tr['lines_at_measure']:,} lines) · blocks after the cutoff "
                  f"{tr['recheck']['blocks_after_cutoff']} (excluded) · first pass {tr['recheck']['first_pass_blocks_identical']}/"
                  f"{tr['recheck']['first_pass_blocks']} byte-identical"},
    ]


def render_report(rc, srcs, audit, dec, seal, findings, win):
    c = rc["classes"]
    t = "# HISTORICAL_PHASE_A_REPORT — FAISAL MASTER FORENSIC RECOVERY · PHASE A\n\n" + HEADER.format(seal=seal["seal_id"], ts=seal["timestamp"])
    t += (f"\n## ⓪ الخلاصة\n- **PHASE_A_STATUS = {seal['status']}** · الختم `{seal['seal_id']}` · حدُّ الأدلّة "
          f"**{seal['evidence_cutoff_utc']}** (ما بعده لا يدخل المرحلة أ · وساعةُ المرحلة ب تبدأ بعده).\n"
          f"- **لا صورةَ لفيصل متاحةٌ خارج المدوّنة:** NEW_TO_CORPUS = {c['NEW_TO_CORPUS']} من {rc['total']} سجلًّا مكتشفًا · "
          f"والمدوّنة {CORPUS_BEFORE} قبل وبعد.\n"
          f"- **وهذا حكمٌ على المتاح وحدَه:** غيرُ المتاح موثَّقٌ بعدده أو «مجهول» (X · قناة تلغرام · الجلسات الأخرى · ما قبل الضغط · "
          "مرفقات الحاوية السابقة · الملفّان PDF) — **لا يُقال «كلّ الصور رُوجعت».**\n")
    t += "\n## ① Sources (A1)\n"
    cs = collections.Counter(s["ACCESS_STATUS"] for s in srcs)
    t += " · ".join(f"{k} {cs.get(k, 0)}" for k in ACCESS) + f" · total {len(srcs)} — `HISTORICAL_SOURCE_ACCESS.md`\n"
    t += "\n## ② Reconciliation (A7)\n```\n" + f"TOTAL {rc['total']} = " + " + ".join(f"{k} {c[k]}" for k in CLASSES) + \
        f"\nREMAINDER {rc['remainder']} · RECOVERED (bytes opened) {rc['recovered']}\n```\n"
    t += "\n## ③ True-new images (A8)\nNone. No forensic extraction was needed; no evidence count changed.\n"
    t += ("\n## ④ Negative evidence (A9)\n**New negative evidence: 0** (no new image). The existing inventory stays authoritative: "
          "NE-01…NE-10 in `faisal_method_v41/corpus_audit/NEGATIVE_EVIDENCE.md`.\n")
    cnt = collections.Counter(r["EVIDENCE_REQUIREMENT"] for r in dec)
    lab = collections.Counter((r["FINAL_DECISION"], r["EVIDENCE_REQUIREMENT"]) for r in dec)
    t += (f"\n## ⑤ Decision forensics (A10) — {len(dec)} historical decision cases (frozen V4 case set `cases_v4.json`)\n"
          + " · ".join(f"**{k}** {cnt.get(k, 0)}" for k in ("CHART_SUFFICIENT", "EXTERNAL_CONTEXT_REQUIRED", "EXTERNAL_CONTEXT_UNKNOWN",
                                                              "DATA_INSUFFICIENT")) + "\n\n")
    rows = []
    for label in ("READY", "WAIT", "REJECT", "UNKNOWN", "MIXED"):
        row = {"FINAL_DECISION": label}
        for k in ("CHART_SUFFICIENT", "EXTERNAL_CONTEXT_REQUIRED", "EXTERNAL_CONTEXT_UNKNOWN", "DATA_INSUFFICIENT"):
            row[k] = lab.get((label, k), 0)
        rows.append(row)
    t += _md_table(rows, ("FINAL_DECISION", "CHART_SUFFICIENT", "EXTERNAL_CONTEXT_REQUIRED", "EXTERNAL_CONTEXT_UNKNOWN", "DATA_INSUFFICIENT"))
    t += ("\nRules (fixed in code, applied mechanically): DATA_INSUFFICIENT = excluded set, UNKNOWN/MIXED label, or no explicit basis · "
          "EXTERNAL_CONTEXT_REQUIRED = Faisal's **own stated reasons** include a non-chart fact (float, short/borrow, news/offering, "
          "split, groups/operator tape, country…) · CHART_SUFFICIENT = every stated reason is chart-derivable (a statement about the "
          "stated basis — unstated context is not excluded) · EXTERNAL_CONTEXT_UNKNOWN = a decision with no classifiable reason. "
          "No case is labelled EXTERNAL merely because the chart does not explain it. Full table: `HISTORICAL_DECISION_FORENSICS.csv`.\n")
    t += "\n## ⑥ Provenance findings recorded by this mission\n" + "".join(f"- {f}\n" for f in findings)
    t += "\n## ⑦ Exhaustiveness audit (A12)\n" + _md_table(audit, ("n", "question", "answer", "evidence"))
    t += (f"\n## ⑧ Evidence cutoff (A14) — {seal['evidence_cutoff_utc']}\n"
          "Every live source was read up to or past the cutoff; nothing dated before it is unread. Evidence after the cutoff is "
          "outside Phase A (and eligible for Phase B under its own rules).\n\n")
    t += _md_table(win, ("SOURCE", "READ_UNTIL", "PROOF"))
    t += ("\n## ⑨ What Phase A does NOT claim\n- It does not claim that every Faisal image ever made was reviewed — only that every "
          "technically accessible source was searched and every accessible image classified.\n- It changes no V4 rule, threshold, label "
          "or configuration, and does not recompute the development percentages (ENGINEERING 92.9% · METHODOLOGY 90.0% · VALIDATION "
          "0.0% · PRODUCTION 0.0% stand as given).\n")
    return t


def render_inventory_csv(records):
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=list(CSV_FIELDS), lineterminator="\n")
    w.writeheader()
    for r in records:
        w.writerow(r)
    return buf.getvalue()


def render_decisions_csv(dec):
    keys = ("CASE_ID", "SET", "TICKERS", "DATE", "SOURCES", "PATTERN", "STRUCTURE", "LOCATION", "CONTEXT", "VALIDITY", "ENTRY",
            "INVALIDATION", "TARGET", "FINAL_DECISION", "EVIDENCE_REQUIREMENT", "REQUIREMENT_BASIS")
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=list(keys), lineterminator="\n")
    w.writeheader()
    for r in dec:
        w.writerow(r)
    return buf.getvalue()


FINDINGS = [
    "**V3.1's «zero missing image» was partly circular:** it counted an owner image as accounted when it matched a *session upload*, "
    "but 13 unique uploads were not in the corpus (4 near-duplicates + 9 unmatched, one of them a Faisal post — UPL_933a9f58). With "
    "the container reset those bytes are now INACCESSIBLE; the Faisal post survives only as text (chart card + V3 transcription).",
    "**This session's own pre-compaction transcript is no longer readable:** 1,000 image blocks measured by V3.1 on 2026-10-02 are "
    "now INACCESSIBLE; owner images sent between that measurement and the compaction (2026-10-02 ≤17:34Z → 21:44Z) are UNKNOWN in number.",
    "**Abbreviated image references were undercounted by the earlier trackers:** the V3.1 rule found 116 text-only IDs; slash lists, "
    "ranges and parenthesised numbers in the catalog add more (all now IMAGE_REFERENCE_ONLY with the rule that found them).",
    "**Telegram intake is fully accounted:** every image message the bot ever received is a saved file or a byte-identical "
    "duplicate (SHA on receipt or the same Telegram file id); permanent failures 0; all collector runs succeeded.",
]


# ── build / check ────────────────────────────────────────────────────────────────────────────────────────────────────
def _write(rel, text):
    p = os.path.join(HERE, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8", newline="") as f:
        f.write(text)


def _read(rel):
    with open(os.path.join(HERE, rel), encoding="utf-8", newline="") as f:
        return f.read()


def render_all(frozen):
    srcs, records, manifest, docrefs, dec, seal = (frozen[k] for k in ("sources", "records", "manifest", "docrefs", "decisions", "seal"))
    inputs, probe, collector = frozen["inputs"], frozen["probe"], frozen["collector"]
    rc = reconcile(records)
    audit = exhaustiveness(rc, srcs, docrefs)
    return {
        OUT["sources"]: render_sources(srcs, seal),
        OUT["recovery"]: render_recovery(inputs, probe, collector, rc, seal),
        OUT["inventory"]: render_inventory_csv(records),
        OUT["reconciliation"]: render_reconciliation(rc, docrefs, seal, audit),
        OUT["v5"]: render_v5(seal),
        OUT["report"]: render_report(rc, srcs, audit, dec, seal, FINDINGS, evidence_window(inputs, probe, collector)),
        OUT["decisions"]: render_decisions_csv(dec),
    }


def _csv_rows(rel):
    return list(csv.DictReader(io.StringIO(_read(rel))))


def load_frozen():
    f = {k: json.loads(_read(v)) for k, v in FROZEN.items()}
    f["records"] = _csv_rows(OUT["inventory"])
    f["decisions"] = _csv_rows(OUT["decisions"])
    f["seal"] = json.loads(_read(OUT["seal"]))
    f["inputs"] = json.loads(_read("data/phase_a_inputs.json"))
    f["probe"] = json.loads(_read("data/artifact_probe_result.json"))
    f["collector"] = f["inputs"]["collector"]
    return f


def validate(frozen):
    """Every invariant the seal promises. Returns a list of problems (empty = sound). Pure on its input + the working tree."""
    P = []
    seal, records, manifest, srcs = frozen["seal"], frozen["records"], frozen["manifest"], frozen["sources"]
    rc = reconcile(records)
    if rc["remainder"]:
        P.append(f"unexplained remainder {rc['remainder']}")
    if rc["duplicate_ids"]:
        P.append(f"duplicate record ids {rc['duplicate_ids'][:3]}")
    for r in records:
        if r["CORPUS_CLASSIFICATION"] not in CLASSES:
            P.append(f"bad class {r['IMAGE_ID']}")
        if r["CORPUS_CLASSIFICATION"] == "EXACT_DUPLICATE" and not r["DUPLICATE_OF_CLASS"]:
            P.append(f"duplicate without target class {r['IMAGE_ID']}")
        if r["BYTES_OPENED_THIS_MISSION"] == "no" and r["CORPUS_CLASSIFICATION"] in ("NEW_TO_CORPUS", "INFORMATIVE_DERIVATIVE"):
            P.append(f"content class without bytes {r['IMAGE_ID']}")
    c = rc["classes"]
    exp = {"total_discovered": rc["total"], "total_recovered": rc["recovered"], "new_to_corpus": c["NEW_TO_CORPUS"],
           "duplicates": c["EXACT_DUPLICATE"], "derivatives": c["INFORMATIVE_DERIVATIVE"], "reference_only": c["IMAGE_REFERENCE_ONLY"],
           "inaccessible": c["INACCESSIBLE_IMAGE"], "missing": c["MISSING_ATTACHMENT"], "non_faisal": c["NON_FAISAL"],
           "unknown": c["UNKNOWN"], "unresolved": rc["remainder"], "source_manifest_hash": canon_hash(srcs),
           "corpus_manifest_hash": canon_hash(manifest), "records_hash": canon_hash(records), "v4_commit": V4_COMMIT,
           "corpus_manifest_count": len(manifest)}
    for k, v in exp.items():
        if seal.get(k) != v:
            P.append(f"seal field {k}: sealed {seal.get(k)!r} ≠ recomputed {v!r}")
    body = {k: v for k, v in seal.items() if k != "seal_id"}
    if seal.get("seal_id") != "PHA-" + canon_hash(body)[:16]:
        P.append("seal_id does not match the seal body")
    try:                                                 # the whole seal — status included — is a function of the frozen data
        again = make_seal(rc, srcs, manifest, records, exhaustiveness(rc, srcs, frozen["docrefs"]), seal["main_commit"],
                          seal["branch_head_at_seal"], seal["timestamp"], seal["telegram_drained_at_seal"], seal["evidence_cutoff_utc"])
        if again != seal:
            P.append("seal differs from its recomputation: " + ", ".join(sorted(k for k in set(again) | set(seal)
                                                                                 if again.get(k) != seal.get(k))))
    except KeyError as e:
        P.append(f"seal field missing: {e}")
    if seal.get("evidence_cutoff_utc") != frozen["probe"].get("listed_at_utc") or \
            seal.get("evidence_cutoff_utc") != frozen["inputs"]["transcript_current"]["recheck"]["cutoff_utc"]:
        P.append("evidence cutoff disagrees with the artifact listing or the transcript cutoff")
    if frozen["inputs"]["transcript_current"]["recheck"]["blocks_after_cutoff"] or \
            frozen["collector"]["cutoff_verification"]["updates_of_any_kind"]:
        P.append("evidence after the cutoff was not excluded or the bot queue was not empty at the cutoff")
    for m in manifest:                                   # historical images are immutable for the epoch
        if m["kind"] != "file":
            continue
        p = _p(m["path"])
        if not os.path.exists(p):
            P.append(f"sealed historical image missing: {m['path']}")
        elif _sha_file(p) != m["sha256"]:
            P.append(f"sealed historical image changed: {m['path']}")
    return P


def check():
    frozen = load_frozen()
    P = validate(frozen)
    for name, text in render_all(frozen).items():
        try:
            cur = _read(name)
        except FileNotFoundError:
            P.append(f"missing artifact {name}")
            continue
        if cur != text:
            P.append(f"artifact differs from its frozen data: {name}")
    for p in P:
        print("⛔", p)
    print("✅ PHASE A check: sound" if not P else f"⛔ PHASE A check: {len(P)} problem(s)")
    return 1 if P else 0


def build(timestamp, main_commit, branch_head):
    inputs = json.loads(_read("data/phase_a_inputs.json"))
    probe = json.loads(_read("data/artifact_probe_result.json"))
    collector = inputs["collector"]
    manifest = corpus_manifest(inputs)
    stems = {m["id"] for m in manifest if m["kind"] == "file"}
    texts = tracked_texts()
    tg_dup = {m["msg"] for m in collector["accounted_records"]}
    refs = scan_references(texts, stems, tg_dup)
    rc_counts = collections.Counter(v["resolution"] for v in refs.values())
    docrefs = {"refs": refs, "counts": {
        "files_scanned": len(texts), "tokens": len(refs), "reference_only": rc_counts["REFERENCE_ONLY"],
        "equivalent": rc_counts["EQUIVALENT_STORED_UNDER_OTHER_NAME"], "telegram_dup": rc_counts["TELEGRAM_DUPLICATE_MESSAGE"],
        "resolved_by_name": rc_counts["RESOLVED_BY_NAME"], "excluded": rc_counts["EXCLUDED"]}}
    srcs = sources(inputs, probe, collector, docrefs)
    records = build_records(inputs, probe, collector, manifest, docrefs)
    dec = decision_forensics()
    for k, obj in (("manifest", manifest), ("sources", srcs), ("docrefs", docrefs)):
        _write(FROZEN[k], json.dumps(obj, ensure_ascii=False, indent=0, sort_keys=True) + "\n")
    _write(OUT["inventory"], render_inventory_csv(records))
    _write(OUT["decisions"], render_decisions_csv(dec))
    if _csv_rows(OUT["inventory"]) != records:            # the seal hashes exactly what is published
        raise SystemExit("⛔ inventory CSV does not round-trip")
    rc = reconcile(records)
    audit = exhaustiveness(rc, srcs, docrefs)
    seal = make_seal(rc, srcs, manifest, records, audit, main_commit, branch_head, timestamp, collector["last_run_id"],
                     probe["listed_at_utc"])
    _write(OUT["seal"], json.dumps(seal, ensure_ascii=False, indent=1, sort_keys=True) + "\n")
    frozen = load_frozen()
    for name, text in render_all(frozen).items():
        _write(name, text)
    P = validate(frozen)
    print(json.dumps({"status": seal["status"], "seal_id": seal["seal_id"], "total": rc["total"], "classes": rc["classes"],
                      "recovered": rc["recovered"], "remainder": rc["remainder"], "problems": P}, ensure_ascii=False))
    return 0 if not P else 1


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("mode", nargs="?", default="check", choices=("build", "check"))
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--timestamp")
    ap.add_argument("--main-commit")
    ap.add_argument("--branch-head")
    a = ap.parse_args(argv)
    if a.check or a.mode == "check":
        return check()
    ts = a.timestamp or dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return build(ts, a.main_commit or "", a.branch_head or "")


if __name__ == "__main__":
    sys.exit(main())
